/// Bridge layer for the admin SDK — thin wrapper over the shared
/// host-bridge primitives in ``@i99dash/sdk``.
///
/// Why a wrapper at all: privileged ops use a different host
/// handler name (``_admin.exec``) than the regular mini-app
/// ``getContext`` call. Everything else — the global
/// names, the legacy fallback, the resolution logic, error classes
/// — is shared with the public SDK. After the Phase-7 dedup audit,
/// this file holds **only** the ``_admin.exec`` shape; nothing
/// duplicated.

import {
  BridgeTransportError,
  HostBridge as _HostBridge,
  NotInsideHostError,
  resolveHostApi,
  type HostBridgeApi,
  type WindowWithHost,
} from '../runtime/index.js';

import type { AdminOpResponse } from './types.js';

// Re-export the shared error types so admin-sdk callers can `catch`
// without also depending on `@i99dash/sdk`. Keeps the public surface
// of admin-sdk self-contained while the implementation reuses the
// canonical classes.
export { BridgeTransportError, NotInsideHostError } from '../runtime/index.js';

/// Ports — anything that satisfies this can stand in for the host.
/// Tests use ``FakeAdminBridge``; production uses ``HostAdminBridge``.
export interface AdminBridge {
  exec<T = unknown>(payload: AdminExecRequest): Promise<AdminOpResponse<T>>;
}

/// Wire shape of one ``_admin.exec`` call.
export interface AdminExecRequest {
  /// Identifier of the command template to invoke. The server's
  /// command-template catalog (see backend ``command_templates``
  /// table) is the source of truth for whether a given id is known
  /// and what tier / step-up it carries.
  templateId: string;
  /// Validated parameters for the template's slots — keys match the
  /// template's `param_schema`. Server re-validates on every cap
  /// call; the client-side type is `object` because shapes vary by
  /// template (no shared schema across all of them).
  params?: Record<string, unknown>;
  /// Capability token from ``/runtime/cap``. Omitted for tier-1
  /// templates.
  capability?: string;
  /// Idempotency key the host echoes into its audit row. Auto-
  /// generated by the client wrapper.
  idempotencyKey: string;
}

/// Real bridge backed by the host-injected global. Reuses
/// ``resolveHostApi`` from the public SDK — same selection rules,
/// same legacy-global fallback, same future deprecation path.
export class HostAdminBridge implements AdminBridge {
  private readonly api: HostBridgeApi;

  constructor(windowLike?: WindowWithHost) {
    const w =
      windowLike ?? (typeof window !== 'undefined' ? (window as WindowWithHost) : undefined);
    if (!w) {
      throw new NotInsideHostError('window is undefined');
    }
    const api = resolveHostApi(w);
    if (!api) {
      throw new NotInsideHostError('host bridge missing on window');
    }
    this.api = api;
  }

  async exec<T = unknown>(payload: AdminExecRequest): Promise<AdminOpResponse<T>> {
    let raw: unknown;
    try {
      raw = await this.api.callHandler('_admin.exec', payload);
    } catch (cause) {
      throw new BridgeTransportError('_admin.exec call failed', cause);
    }
    return raw as AdminOpResponse<T>;
  }
}

/// Test/dev bridge — back the SDK with a stubbed handler map. The
/// dev-server (``@i99dash/sdk-dev-server``) plumbs this via the same
/// shape so devs can iterate without a real device.
export class FakeAdminBridge implements AdminBridge {
  private readonly handler: (req: AdminExecRequest) => Promise<AdminOpResponse<unknown>>;

  constructor(handler: (req: AdminExecRequest) => Promise<AdminOpResponse<unknown>>) {
    this.handler = handler;
  }

  async exec<T = unknown>(payload: AdminExecRequest): Promise<AdminOpResponse<T>> {
    return (await this.handler(payload)) as AdminOpResponse<T>;
  }
}

/// Compatibility re-export: keep the old ``HostBridge`` symbol from
/// ``@i99dash/sdk`` reachable from the admin package without
/// importing both.
export { _HostBridge as HostBridge };
